### ISSUE TITLE
Missing required field on MediaPackage OriginEndpointArgs

### ISSUE THREAD

**Issue by alfred-stokespace** [pulumi/pulumi-aws-native#1036]
### What happened?

I try to create a simple OriginEndpoint and I fillout out every required attribute as far as your interface suggests https://github.com/pulumi/pulumi-aws-native/blob/360bc11ff2538e17bacfb34c512cd1b34ef7ba50/sdk/nodejs/mediapackage/originEndpoint.ts#L140

with code like ...
```
const originEndpoint = new OriginEndpoint(`my-test-origin-endpoint`,
    {
        channelId: channelId,
        hlsPackage: {
            adMarkers: OriginEndpointHlsPackageAdMarkers.None,
            adTriggers: [
                OriginEndpointHlsPackageAdTriggersItem.SpliceInsert,
                OriginEndpointHlsPackageAdTriggersItem.ProviderAdvertisement,
                OriginEndpointHlsPackageAdTriggersItem.DistributorAdvertisement,
                OriginEndpointHlsPackageAdTriggersItem.ProviderPlacementOpportunity,
                OriginEndpointHlsPackageAdTriggersItem.DistributorPlacementOpportunity
            ],
            adsOnDeliveryRestrictions: OriginEndpointAdsOnDeliveryRestrictions.Restricted,
            includeDvbSubtitles: false,
            includeIframeOnlyStream: false,
            playlistType: OriginEndpointHlsPackagePlaylistType.Event,
            playlistWindowSeconds: 60,
            programDateTimeIntervalSeconds: 0,
            segmentDurationSeconds: 6,
            streamSelection: {
                maxVideoBitsPerSecond: 2147483647,
                minVideoBitsPerSecond: 0,
                streamOrder: OriginEndpointStreamSelectionStreamOrder.VideoBitrateAscending
            },
            useAudioRenditionGroup: false
        },
        manifestName: "index",
        origination: OriginEndpointOrigination.Allow,
        startoverWindowSeconds: 0,
        timeDelaySeconds: 0
    })
```

I try and pulumi up and I get...
```
 aws-native:mediapackage:OriginEndpoint (my-test-origin-endpoint):
    error: creating resource: operation error CloudControl: CreateResource, https response error StatusCode: 400, RequestID: e6dcdea0-c74e-468b-a924-bcf6
7ed0c856, api error ValidationException: Model validation failed (#: #: only 1 subschema matches out of 2
    #: required key [Id] not found)
```

### Expected Behavior

As per the AWS official documentation 
https://docs.aws.amazon.com/cli/latest/reference/mediapackage/create-origin-endpoint.html

I should be able to supply an id string and get a successful creation of an origin endpoint

### Steps to reproduce

I mentioned this in the description

### Output of `pulumi about`

```
Dependencies:
NAME                VERSION
@pulumi/aws-native  0.73.0
@pulumi/aws         5.42.0
@pulumi/awsx        1.0.4
@pulumi/pulumi      3.78.1
@types/node         16.18.40

```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by rquitales** [comment]
Hello @alfred-stokespace,

We appreciate you bringing up this issue and providing a workaround. It seems that the root of the problem lies in the CloudFormation API spec that we utilize upstream. Indeed, the necessary `id` field is present in the spec, as can be seen here: [aws-mediapackage-originendpoint.json Lines 14-20](https://github.com/pulumi/pulumi-aws-native/blob/360bc11ff2538e17bacfb34c512cd1b34ef7ba50/aws-cloudformation-schema/aws-mediapackage-originendpoint.json#L14-L20). However, during code generation, the `id` field is omitted due to clashes with Pulumi's internal use of the `id` field name. This is causing the missing field issue you've encountered.

To resolve this, we'll need to update the provider in such a way that this field is appropriately aliased, possibly to something like `OriginEndpointID`. This should prevent any conflicts and ensure that the necessary field is properly recognized and can still be used.

Your understanding and patience are greatly appreciated as we work on implementing this change. You are also welcome to help create a PR and we'd be more than happy to help shepherd it along. If you have any further insights or questions, feel free to share.

Thank you for your report, and we look forward to providing a solution to this issue in the near future.

**Comment by alfred-stokespace** [comment]
> Hello @alfred-stokespace,
> 
> We appreciate you bringing up this issue and providing a workaround. It seems that the root of the problem lies in the CloudFormation API spec that we utilize upstream. Indeed, the necessary `id` field is present in the spec, as can be seen here: [aws-mediapackage-originendpoint.json Lines 14-20](https://github.com/pulumi/pulumi-aws-native/blob/360bc11ff2538e17bacfb34c512cd1b34ef7ba50/aws-cloudformation-schema/aws-mediapackage-originendpoint.json#L14-L20). However, during code generation, the `id` field is omitted due to clashes with Pulumi's internal use of the `id` field name. This is causing the missing field issue you've encountered.
> 
> To resolve this, we'll need to update the provider in such a way that this field is appropriately aliased, possibly to something like `OriginEndpointID`. This should prevent any conflicts and ensure that the necessary field is properly recognized and can still be used.
> 
> Your understanding and patience are greatly appreciated as we work on implementing this change. You are also welcome to help create a PR and we'd be more than happy to help shepherd it along. If you have any further insights or questions, feel free to share.
> 
> Thank you for your report, and we look forward to providing a solution to this issue in the near future.

thanks for responding. Good to hear that I found a legit issue as opposed to me not reading the docs correctly :)
