### ISSUE TITLE
AWS::IAM::Role is not yet supported via Cloud Control API

### ISSUE THREAD

**Issue by shubhambirvatkar700** [pulumi/pulumi-aws-native#1047]
i'm getting similar issue to import existing iam role into pulumi
command used --> pulumi import aws-native:iam:Role lambda-role <role arn> --yes
Error --->

  aws-native:iam:Role (lambda-role):
    error: Preview failed: operation error CloudControl: GetResource, https response error StatusCode: 400, RequestID: 4a926ad4-d361-48ae-9804-473b2df50879, UnsupportedActionException: The resource AWS::IAM::Role is not yet supported via Cloud Control API
    
 Dependency --> 
 aws-native-0.61.0
 aws-5.42.0
pulumi (3.66.0 )

Please note --> It was working couple of days back and now its failing

_Originally posted by @shubhambirvatkar700 in https://github.com/pulumi/pulumi-aws-native/issues/844#issuecomment-1689298220_

**Comment by shubhambirvatkar700** [comment]
Note --> This is specific to only eu-central-1 region. i'm able to import it in another region.

**Comment by matwerber1** [comment]
Hi, 

I happened to find this thread while searching the same "The resource AWS::IAM::Role is not yet supported via Cloud Control API" error. 

I encountered this error with the latest AWS SDK v3 in NodeJS and was able to resolve it by setting the SDK client's region to `us-east-1` instead of my default `us-west-2`. 

Yes, IAM resources are "global", but the IAM control plane is actually entirely within `us-east-1`. When you create an IAM resource like a role, that process takes place in us-east-1. The us-east-1 region is the source of truth, and the role info is subsequently propogated to the other AWS regions around the globe so that region-specific services don't have to send requests to a separate region. [See docs](https://docs.aws.amazon.com/whitepapers/latest/aws-fault-isolation-boundaries/global-services.html). 

At least in NodeJS, this seems isolated to the Cloud Control library, as the regular IAM library doesn't complain:

```js
import { fromSSO } from "@aws-sdk/credential-provider-sso"; // for profiles using AWS SSO
import CC from "@aws-sdk/client-cloudcontrol";
import IAM from "@aws-sdk/client-iam";

const awsProfile = process.env.AWS_DEFAULT_PROFILE;

// Cloud Control
const ccClient = new CC.CloudControlClient({
  credentials: fromSSO({
    profile: awsProfile,
  }),
  region: "us-west-2",    // us-west-2 = FAIL, us-east-1 = SUCCEED
});

// IAM-specific library
const iamClient = new IAM.IAMClient({
  credentials: fromSSO({
    profile: awsProfile,
  }),
  region: "us-west-2",  // us-west-2 = SUCCEED, us-east-1 = SUCCEED
});
```

Similar results with the AWS CLI: 

```sh
# FAIL
aws cloudcontrol list-resources --type-name "AWS::IAM::Role" --region us-west-2 

# SUCCEED
aws cloudcontrol list-resources --type-name "AWS::IAM::Role" --region us-east-1
aws iam list-roles --region us-east-1
aws iam list-roles --region us-west-2
```

I haven't verified, but my guess is that the AWS CLI and native IAM client libraries have code somewhere that overrides whatever region you've configured and forces us-east-1 before making API calls, and that the Cloud Control implementation has not put this logic in place.

**Comment by mikhailshilkov** [comment]
@shubhambirvatkar700 @matwerber1 We checked in with folks from AWS and they let us know that this was a problem on the Cloud Control API side but it's been fixed since. Are you still experiencing this issue, or can we close it out?

**Comment by mikhailshilkov** [comment]
Since we haven't seen this in a while, I'll close the issue as fixed on the AWS side
