### ISSUE TITLE
[provider] Implement endpoints

### ISSUE THREAD

**Issue by lblackstone** [pulumi/pulumi-aws-native#108]
The `endpoints` parameter is not yet implemented. 

**_Please upvote this issue if you need this feature. This helps us to determine roadmap priorities._**

**Comment by chris-stetter** [comment]
> This is super useful for our integration tests, which are running against Localstack (simulated AWS environment) locally.
> 
> Also, this is now the top-voted issue 😏

Due to the same reason we cannot use native unfortunately.

**Comment by cabeaulac** [comment]
This just bit me with our Localstack integration.

**Comment by mikhailshilkov** [comment]
I'd love to engage to potential customers of this feature to understand the exact requirements and expectation from it. I don't think we can map the configuration parameter from AWS Classic 1:1.

To the contrary to the classic provider, AWS Native has a single endpoint for all resource operations: AWS Cloud Control API. Do folks want to override that single endpoint? Or is there configuration beyond that?

**Comment by sverch** [comment]
It looks like terraform allows for [overriding just that api](https://registry.terraform.io/providers/hashicorp/aws/5.1.0/docs/guides/custom-service-endpoints.html#cloudcontrol), and [localstack seems to support it](https://github.com/localstack/localstack/commit/d3f1102c68be7b799224cf7d5e738a96d7c32acc#diff-dd72c8c7cb56aa6d644a4619bf94518a6d4d51e9f267b3dd30e89bb8bb75355a). I suspect that pointing requests to the local endpoint would do it, and the local service should handle it properly if it's truly emulating the aws API.

**Comment by mikhailshilkov** [comment]
> It looks like terraform allows for [overriding just that api](https://registry.terraform.io/providers/hashicorp/aws/5.1.0/docs/guides/custom-service-endpoints.html#cloudcontrol)

Yes, Terraform's implementation is notably different from AWS Native. They use direct service endpoints, while our native provider goes through Cloud Control API.

**Comment by sverch** [comment]
Do you mean that behind the scenes they are using the service endpoints to implement the [cloud control api resource](https://registry.terraform.io/providers/hashicorp/aws/5.1.0/docs/resources/cloudcontrolapi_resource), or do you mean that rather than implementing it as a single resource, the AWS Native implementation provides a higher level API that routes to that underneath?

I would imagine that ultimately the request payload is a cloud control API object that is sent to the endpoint, where the object itself has service information. If that endpoint is a local service like localstack, I'd expect localstack to know how to interpret that request properly and "create" that resource in its local state.

**Comment by mikhailshilkov** [comment]
> behind the scenes they are using the service endpoints to implement the [cloud control api resource](https://registry.terraform.io/providers/hashicorp/aws/5.1.0/docs/resources/cloudcontrolapi_resource)

I wasn't talking about `aws_cloudcontrolapi_resource` specifically. I think what this issue is asking for is being able to set a custom endpoint e.g. for s3, or for ecs, etc - a custom endpoint per AWS service. 

> I would imagine that ultimately the request payload is a cloud control API object that is sent to the endpoint, where the object itself has service information. If that endpoint is a local service like localstack, I'd expect localstack to know how to interpret that request properly and "create" that resource in its local state.

Yeah, we could allow you to override the Cloud Control API endpoint specifically. So, it would be a single endpoint value to set. Is that what you are asking for?

**Comment by sverch** [comment]
> I wasn't talking about aws_cloudcontrolapi_resource specifically. I think what this issue is asking for is being able to set a custom endpoint e.g. for s3, or for ecs, etc - a custom endpoint per AWS service.

That's true, as the issue description is written, but my understanding of what you're saying is that pulumi implements the creation of those resources by converting them to requests to the cloud control API, is that right?

> Yeah, we could allow you to override the Cloud Control API endpoint specifically. So, it would be a single endpoint value to set. Is that what you are asking for?

That's correct. I can't speak for others, but I use this as a "local test mode", so I either set all endpoints to the local service, or none of them, even when I have the ability to set them one at a time.

It's hard to think of a use case where I want some requests going to AWS, and some requests going to a local endpoint depending on the resource. If someone did have that use case, I believe they could work around it by creating different providers for different situations (e.g., a "myCustomS3Deployment" provider that they use only when creating s3 resources).
