### ISSUE TITLE
Missing fields on ExperimentTemplateTargetMapArgs

### ISSUE THREAD

**Issue by iwahbe** [pulumi/pulumi-aws-native#1199]
### What happened?

I was answering a [bug report on `pulumi-aws`](https://github.com/pulumi/pulumi-aws/issues/3059#issuecomment-1834909764). I suggested that there is an equivalent type in `pulumi-aws-native`. Unfortunately, the `was-native` type seems to be unusable. We are interested in the `target` field of `fix.ExperimentTemplate`:
https://github.com/pulumi/pulumi-aws-native/blob/d0352f596806db4e2f537e946372c391b41967e7/sdk/python/pulumi_aws_native/fis/experiment_template.py#L16-L29

When we drill down into the type of `ExperimentTemplateTargetMapArgs`, it's empty:

https://github.com/pulumi/pulumi-aws-native/blob/d0352f596806db4e2f537e946372c391b41967e7/sdk/python/pulumi_aws_native/fis/_inputs.py#L142-L149

It's also missing from the registry.

### Example

I raised this issue because of https://github.com/pulumi/pulumi-aws/issues/3059#issuecomment-1834909764.

### Output of `pulumi about`

NA

### Additional context

The output type `ExperimentTemplateTargetMap` is also empty, but it inherits from `dict` so it might be usable.

https://github.com/pulumi/pulumi-aws-native/blob/d0352f596806db4e2f537e946372c391b41967e7/sdk/python/pulumi_aws_native/fis/outputs.py#L169-L179

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by danielrbradley** [comment]
I believe this has now been fixed in the following PR:
- https://github.com/pulumi/pulumi-aws-native/pull/1363

Targets is now defined as:
https://github.com/pulumi/pulumi-aws-native/blob/b46b6fb7d2867a28f7347025c655c57835ac533d/sdk/python/pulumi_aws_native/fis/experiment_template.py#L24

Where the type now has additional fields present:

https://github.com/pulumi/pulumi-aws-native/blob/b46b6fb7d2867a28f7347025c655c57835ac533d/sdk/python/pulumi_aws_native/fis/_inputs.py#L280-L301
