### ISSUE TITLE
aws-native schema mangles capitalized acronyms at start of property names

### ISSUE THREAD

**Issue by kmosher** [pulumi/pulumi-aws-native#650]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

The name re-styling done to properties doesn't seem to properly grok acronyms at the start of property names (which are represented in all caps in Cloudformation's camel case style). [For example](https://www.pulumi.com/registry/packages/aws-native/api-docs/networkfirewall/rulegroup/#rulegrouprulevariables) `IPSets` becomes

* `iPSets` in Typescript, Java, and YAML _(should be `ipSets`)_
* `i_p_sets` in Python _(should be `ip_sets`)_

grepping around the python SDK for strings like `i_p_`, `a_c_l`, `h_a_` shows this to be a problem on multiple resources. Including [this wonderful example](https://www.pulumi.com/registry/packages/aws-native/api-docs/memorydb/acl/#a_cl_name_python) in `memorydb` where `ACLName` somehow first gets mangled to `aCLName` before being regularized into Python resulting in `a_cl_name`.

As demonstrated by that example though, runs of capitals elsewhere in property names seem to be handled correctly as single words. Though, it seems like there might still be some other bugs related to camelCase parsing in other bits of codegen like [for example](https://github.com/pulumi/pulumi-aws-native/blob/1ae4a4d9c2256b2a79ca536f8d8497b28d10e4c3/sdk/python/pulumi_aws_native/wafv2/get_web_aclassociation.py#L32) `get_web_aclassociation()` instead of `get_web_acl_association()`.

**Comment by kmosher** [comment]
This (and related functions) seems to be the culprit(s):
https://github.com/pulumi/pulumi-aws-native/blob/59ae7ff6941728b0761135ff409cc9b720a05005/provider/pkg/schema/naming.go#L11

```go
// ToSdkName converts a Cloud Formation property or attribute name to the lowerCamelCase convention that
// is used in Pulumi schema's properties.
func ToSdkName(s string) string {
	if r := rune(s[0]); r >= 'A' && r <= 'Z' {
		s = strings.ToLower(string(r)) + s[1:]
	}
	return s
}
```

**Comment by danielrbradley** [comment]
Adding context from @viveklak 

> FWIW we might have similar issues in other native providers as well but azure/google have the escape hatch of https://github.com/pulumi/pulumi-azure-native/blob/master/provider/pkg/gen/utilities.go#L96-L99

```
var uppercaseAcronym = map[string]bool{
	"ID":  true,
	"TTL": true,
}
```

**Comment by danielrbradley** [comment]
It would be good to know how wide-ranging the impact would be. If it's limited to a couple of specific resources, then we can probably just changelog it, but if it affects a large surface area we might need to consider this as part of a major version bump to help communicate the breaking change via the semantic versioning.

**Comment by viveklak** [comment]
> It would be good to know how wide-ranging the impact would be. If it's limited to a couple of specific resources, then we can probably just changelog it, but if it affects a large surface area we might need to consider this as part of a major version bump to help communicate the breaking change via the semantic versioning.

As aws-native is still in preview I think we might be ok to changelog this and fix it without requiring a major version bump?

**Comment by danielrbradley** [comment]
> As aws-native is still in preview I think we might be ok to changelog this and fix it without requiring a major version bump?

Even though it's in preview, I'm unclear on what the current usage is like so just want to keep that in mind in case this ends up being more disruptive. Another option if it looks disruptive could be if we can add the fixed casing alongside and deprecate the old spellings.

**Comment by mikhailshilkov** [comment]
I took another look at the issue and we need to get it solved, since it's affecting a bunch of resources and properties.

The fix should land in https://github.com/pulumi/pulumi-aws-native/blob/b7f77bdfbc864c0df5cab8e8b672d6a37905f3f3/provider/pkg/schema/naming.go#L11

Right now, we simply lowercase the first character, which is wrong for prefixes like `IP` or `DB`. It would be fairly straightforward to lowercase all the upper characters in a prefix, or have a list of well-known abbreviations similar to what is suggested in https://github.com/pulumi/pulumi-aws-native/issues/650#issuecomment-1275758778

However, the tricky bit is that we need to keep https://github.com/pulumi/pulumi-aws-native/blob/b7f77bdfbc864c0df5cab8e8b672d6a37905f3f3/provider/pkg/schema/naming.go#L20 do the inverse operation reliably, and there is no way to restore `ipAddress` either into `IpAddress` or `IPAddress` reliably. To solve this, we probably need to add CFN name as a metadata to https://github.com/pulumi/pulumi-aws-native/blob/b7f77bdfbc864c0df5cab8e8b672d6a37905f3f3/provider/pkg/schema/metadata.go#L17-L18 and use that name at runtime for all conversions.

**Comment by danielrbradley** [comment]
A somewhat related topic I was discussing with @Frassle was to define a stricter internal naming mechanism which preserves initialism for all languages. The approach was to:
1. Use underscores to separate words
2. Normal words are always lowercase
3. Initialisms are all uppercase

E.g. `get_web_ACL_association` or `IP_address`.

From this form we can reliably generate all language's variations. For wider application we'd need work in pu/pu to support this, but perhaps we can take advantage of the approach in just this provider?

**Comment by Frassle** [comment]
> but perhaps we can take advantage of the approach in just this provider?

This would need work in pu/pu but we could expose this as a schema option, and just opt aws-native in first.

**Comment by mjeffryes** [comment]
I agree that it would be worth defining an internal naming mechanism that would better communicate word breaks and casing. 

I don't think it's really practical to define it as "Normal words are always lowercase, Initialisms are all uppercase" however. That requires the provider to distinguish words from initialisms in the source, where in practice, the source itself is inconsistent wrt. the casing of initialisms. (eg. AWS schema uses all of these: "ARN", "Arn", "Arns" and "ARNs") Instead, I think we'd just want to use underscores for word breaks and follow the source for casing.

I'm willing to try implementing this as a schema option in pu/pu, but I'm not sure about the cost/benefit. If we'd adopt the new internal naming mechanism to resolve similar problems in other providers, it's probably worth it. If it would only be used in aws-native, I think we have a path for making the exiting naming system work here, even if it's less ideal.

**Comment by Frassle** [comment]
> I think we'd just want to use underscores for word breaks and follow the source for casing.

We can't really do that. Different languages have different expectations for casing acronyms. E.g. C# would use name "GetWebAclAssociation", Python "get_web_acl_association", Go "GetWebACLAssociation".

> the source itself is inconsistent 

Yes, that's a problem for each provider to work out how to solve, but they should have the domain specific knowlege to do so. E.g. in this case mapping any casing combination of "arn"/"ARN"/"Arn" to "ARN".

> If we'd adopt the new internal naming mechanism to resolve similar problems in other providers

This is a common problem across all providers, it wouldn't just be aws-native. My comment was purely that aws-native could be the first use case for it, not the only use case.

**Comment by mjeffryes** [comment]
>> I think we'd just want to use underscores for word breaks and follow the source for casing.
>
> We can't really do that. Different languages have different expectations for casing acronyms. E.g. C# would use name "GetWebAclAssociation", Python "get_web_acl_association", Go "GetWebACLAssociation".

I understand that we'd need to honor the different casing expectations of the various target languages when generating, to lowercase or CamelCase initialisms that are all uppercase in the source, but I'm not sure it's practical to expect the provider to identify all initialisms via casing.

>> the source itself is inconsistent
>
> Yes, that's a problem for each provider to work out how to solve, but they should have the domain specific knowlege to do so. E.g. in this case mapping any casing combination of "arn"/"ARN"/"Arn" to "ARN".

That's certainly possible, but doesn't seem terribly practical given the number of providers and number of ids involved. In practice, it seems likely that some lowercase initialisms will tend to sneak though;  e.g. we'll likely end up with at least some initialisms in Go that don't get capitalized. It might be better if we just told users in languages that expect uppercase initialisms that we'll follow the casing of the source for initialisms, rather than breaking convention by accident.

I've also explored using lowerCamelCase for all initialisms as I've experimented with this code. That provides consistency, with the downside that some initialisms look a little weird that way, eg. `DesiredEc2Instances`

**Comment by Frassle** [comment]
> but I'm not sure it's practical to expect the provider to identify all initialisms via casing.

Indeed, they probably can't. But neither can codegen, at least the providers have some domain knowledge they can use to help.

There's also the benefit of making sure this complexity is only needed in one place, writing the schema, and that all users of schema don't need to re-apply some normalizing function as they read names off the schema.

I'm not totally sure what the naming system should be (words_and_ACRONYMS was mine and Dan's first guess towards this). But it's clear the current system of trying to infer things from "PascalAndACRONYMS" is problematic.

**Comment by mjeffryes** [comment]
FWIW, I agree that switching to "_" as a word separator in our internal schema would reduce ambiguity and simplify codegen; seems like a clear win.
