### ISSUE TITLE
WebACLCustomResponseBodiesArgs type not implemented

### ISSUE THREAD

**Issue by smirco-globality** [pulumi/pulumi-aws-native#734]
## Hello!
- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

wafv2 WebACL has a parameter for custom_response_bodies accepting type WebACLCustomResponseBodiesArgs
however this input type appears to simply be a stub https://github.com/pulumi/pulumi-aws-native/blob/master/sdk/python/pulumi_aws_native/wafv2/_inputs.py#L2550-L2557

This makes it impossible to manage custom responses on WafACLs

**Comment by roothorp** [comment]
Hi @smirco-globality, thanks for the issue! I've raised this with the team to be prioritized and added to our work stack.

**Comment by danielrbradley** [comment]
I believe this has now been fixed in the following PR:
- https://github.com/pulumi/pulumi-aws-native/pull/1363

The type of `custom_response_bodies` is now defined as:
https://github.com/pulumi/pulumi-aws-native/blob/b46b6fb7d2867a28f7347025c655c57835ac533d/sdk/python/pulumi_aws_native/wafv2/web_acl.py#L116

with the type definition:

https://github.com/pulumi/pulumi-aws-native/blob/b46b6fb7d2867a28f7347025c655c57835ac533d/sdk/python/pulumi_aws_native/wafv2/_inputs.py#L3034-L3060
